apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nancy-vr-video-streamer.fullname" . }}-videos-pvc
  labels:
    {{- include "nancy-vr-video-streamer.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.videos.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nancy-vr-video-streamer.fullname" . }}-logs-pvc
  labels:
    {{- include "nancy-vr-video-streamer.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
