apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nancy-vr-video-streamer.serviceAccountName" . }}
  labels:
    {{- include "nancy-vr-video-streamer.labels" . | nindent 4 }}
automountServiceAccountToken: true
